
plt.figure()
ax1 = plt.plot(t, err0, color="r", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('Position x error')
plt.figure()
ax2 = plt.plot(t, err1, color="black", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('Position y error')
plt.figure()
ax3 = plt.plot(t, err2, color="blue", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('Position z error')
plt.figure()
ax4 = plt.plot(t, err3, color="brown", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('velocity x error')
plt.figure()
ax5 = plt.plot(t, err4, color="cyan", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('velocity y error')
plt.figure()
ax6 = plt.plot(t, err5, color="darkred", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('velocity z error')
plt.figure()
ax7 = plt.plot(t, err6, color="dimgray", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel(' phi error')
plt.figure()
ax8 = plt.plot(t, err7, color="hotpink", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('theta error')
plt.figure()
ax9 = plt.plot(t, err8, color="maroon", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('psi error')
plt.figure()
ax10 = plt.plot(t, err9, color="purple", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('p error')
plt.figure()
ax11 = plt.plot(t, err10, color="salmon", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('q error')
plt.figure()
ax12 = plt.plot(t, err11, color="sandybrown", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('r error')
plt.figure()
plt.plot(t,x ,label="kalman x", color="red", linestyle="-", linewidth=1.0)
plt.plot(t,rx , label = "real rx",color="blue", linestyle="-", linewidth=1.0)

plt.xlabel('Time')
plt.ylabel('x')
plt.figure()
plt.plot(t,y , color="sandybrown", linestyle="-", linewidth=1.0)
plt.plot(t,ry , color="blue", linestyle="-", linewidth=1.0)
plt.xlabel('Time')
plt.ylabel('y')

plt.show()


ax[0].plot(t, x , color="r", linestyle="--", linewidth=2.0,label='x')
ax[0].plot(t, y , color="brown", linestyle="--", linewidth=2.0,label='y')
ax[0].plot(t, z , color="blue", linestyle="--", linewidth=2.0,label='z')
plt.legend(loc = 'best')
ax[1].plot(t, rx,color="r", linestyle="--", linewidth=2.0,label='x')
ax[1].plot(t, ry , color="brown", linestyle="--", linewidth=2.0,label='y')
ax[1].plot(t, rz , color="blue", linestyle="--", linewidth=2.0,label='z')
#plt.plot(t, rx, color="blue", linestyle=":", linewidth=2.0,label='true position x')
#plt.plot(t, err0, color="black", linestyle="-", linewidth=2.0,label='Pos x error')
plt.legend(loc = 'best')
plt.xlabel('Time')
plt.ylabel('Position x ')
